/*
 * QueueView.java
 *
 * Created on 14/10/2010, 11:36:55 AM
 */
package com.ettrema.backup;

import com.ettrema.backup.config.Repo;
import com.ettrema.backup.config.DavRepo;
import com.ettrema.backup.config.Root;
import java.util.ArrayList;
import java.util.List;
import com.ettrema.backup.config.Config;
import com.ettrema.backup.account.AccountCreator;
import com.ettrema.backup.config.Job;
import javax.swing.ImageIcon;
import com.ettrema.backup.engine.Engine;
import com.ettrema.backup.engine.FileWatcher;
import com.ettrema.backup.queue.QueueManager;
import com.ettrema.event.EventManager;
import com.ettrema.httpclient.ProxyDetails;
import org.jdesktop.application.Action;

import static com.ettrema.backup.BackupApplication._;

/**
 *
 * @author brad
 */
public class AccountView extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	private final Engine engine;
	private final EventManager eventManager;
	private final Config config; // only provided when no job given
	private final Job job;

	/**
	 * To update the given job
	 * @param engine
	 * @param eventManager
	 * @param job
	 * @param accountCreator
	 * @param proxyDetails 
	 */
	public AccountView(Engine engine, EventManager eventManager, Job job, AccountCreator accountCreator, ProxyDetails proxyDetails) {
		this("Modify account", engine, eventManager, job, null, accountCreator, proxyDetails);
	}

	/**
	 * For creating a new job
	 * 
	 * @param engine
	 * @param eventManager
	 * @param config
	 * @param accountCreator
	 * @param proxyDetails 
	 */
	public AccountView(Engine engine, EventManager eventManager, Config config, AccountCreator accountCreator, ProxyDetails proxyDetails) {
		this("New account", engine, eventManager, null, config, accountCreator, proxyDetails);
	}

	private AccountView(String title, Engine engine, EventManager eventManager, Job job, Config config, AccountCreator accountCreator, ProxyDetails proxyDetails) {
		this.engine = engine;
		this.eventManager = eventManager;
		this.job = job;
		this.config = config;
		this.setTitle(title);
		initComponents();

		ImageIcon imageIcon = new ImageIcon(getClass().getResource("/logo16x16.png"), "");
		setIconImage(imageIcon.getImage());

		userPanel.setAccountCreator(accountCreator);
		userPanel.setProxyDetails(proxyDetails);

		this.setSize(650, 720);
		if (job != null) {
			userPanel.load(job);
			backupLocations1.load(job);
		}
	}

	@Action
	public void doSave() {
		System.out.println("doSave");
		if( !isValidSettings()) {
			return ;
		}
		String jobName = userPanel.getAccountName() + "@" + userPanel.getHostName();
		Job jobToSave = this.job;
		if (jobToSave == null) {
			DavRepo davRepo = new DavRepo();
			List<Root> roots = new ArrayList<Root>();
			List<Repo> repos = new ArrayList<Repo>();
			repos.add(davRepo);
			jobToSave = new Job(jobName, repos, roots);
			jobToSave.setConfig(config);
			davRepo.setJob(jobToSave);

			config.getJobs().add(jobToSave);
		}
		engine.cancelScan(); // if scanning, cancel it so new changes can take effect
		String accPath = config.getMediaLoungePath(userPanel.getAccountName());
		userPanel.save(accPath, jobToSave);		
		backupLocations1.save("", jobToSave);
		jobToSave.getConfig().save();
		_(FileWatcher.class).scanNow();
		_(QueueManager.class).setPaused(false);
		doClose();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlOuter = new javax.swing.JPanel();
        userPanel = new com.ettrema.backup.ExistingUserPanel();
        backupLocations1 = new com.ettrema.backup.BackupLocations();
        pnlButtons = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        btnCancel = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        btnOk = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.ettrema.backup.BackupApplication.class).getContext().getResourceMap(AccountView.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setForeground(resourceMap.getColor("Form.foreground")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        pnlOuter.setBackground(resourceMap.getColor("pnlOuter.background")); // NOI18N
        pnlOuter.setName("pnlOuter"); // NOI18N

        userPanel.setAlignmentX(1.0F);
        userPanel.setName("userPanel"); // NOI18N

        backupLocations1.setAlignmentX(1.0F);
        backupLocations1.setName("backupLocations1"); // NOI18N

        pnlButtons.setBackground(resourceMap.getColor("pnlButtons.background")); // NOI18N
        pnlButtons.setAlignmentX(1.0F);
        pnlButtons.setMaximumSize(new java.awt.Dimension(32767, 100));
        pnlButtons.setMinimumSize(new java.awt.Dimension(10, 100));
        pnlButtons.setName("pnlButtons"); // NOI18N
        pnlButtons.setPreferredSize(new java.awt.Dimension(10, 30));
        pnlButtons.setLayout(new javax.swing.BoxLayout(pnlButtons, javax.swing.BoxLayout.LINE_AXIS));

        filler1.setName("filler1"); // NOI18N
        pnlButtons.add(filler1);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.ettrema.backup.BackupApplication.class).getContext().getActionMap(AccountView.class, this);
        btnCancel.setAction(actionMap.get("doClose")); // NOI18N
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.setPreferredSize(new java.awt.Dimension(100, 25));
        pnlButtons.add(btnCancel);

        filler2.setName("filler2"); // NOI18N
        pnlButtons.add(filler2);

        btnOk.setAction(actionMap.get("doSave")); // NOI18N
        btnOk.setText(resourceMap.getString("btnOk.text")); // NOI18N
        btnOk.setName("btnOk"); // NOI18N
        btnOk.setPreferredSize(new java.awt.Dimension(100, 25));
        pnlButtons.add(btnOk);

        lblHeading.setFont(resourceMap.getFont("lblHeading.font")); // NOI18N
        lblHeading.setForeground(resourceMap.getColor("lblHeading.foreground")); // NOI18N
        lblHeading.setText(resourceMap.getString("lblHeading.text")); // NOI18N
        lblHeading.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblHeading.setName("lblHeading"); // NOI18N

        javax.swing.GroupLayout pnlOuterLayout = new javax.swing.GroupLayout(pnlOuter);
        pnlOuter.setLayout(pnlOuterLayout);
        pnlOuterLayout.setHorizontalGroup(
            pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOuterLayout.createSequentialGroup()
                .addGroup(pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOuterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
                    .addGroup(pnlOuterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backupLocations1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, Short.MAX_VALUE))
                    .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addGroup(pnlOuterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pnlOuterLayout.setVerticalGroup(
            pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOuterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backupLocations1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlOuter);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	@Action
	public void doClose() {
		this.setVisible(false);
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ettrema.backup.BackupLocations backupLocations1;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlOuter;
    private com.ettrema.backup.ExistingUserPanel userPanel;
    // End of variables declaration//GEN-END:variables

	private boolean isValidSettings() {
		return userPanel.validateStep();
	}
}
