/*
 * ProxyForm.java
 *
 * Created on 9/11/2010, 9:05:35 AM
 */
package com.ettrema.backup;

import com.ettrema.httpclient.ProxyDetails;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author brad
 */
public class ProxyForm extends javax.swing.JDialog {

    private final ProxyDetails proxyDetails;

    /** Creates new form ProxyForm */
    public ProxyForm( java.awt.Frame parent, boolean modal, ProxyDetails proxyDetails ) {
        super( parent, modal );
        this.proxyDetails = proxyDetails;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proxyGroup = new javax.swing.ButtonGroup();
        pnlOuter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radUseSystem = new javax.swing.JRadioButton();
        radUseCustomSettings = new javax.swing.JRadioButton();
        lblProxyHost = new javax.swing.JLabel();
        lblProxyPort = new javax.swing.JLabel();
        lblProxyPort1 = new javax.swing.JLabel();
        lblProxyPort2 = new javax.swing.JLabel();
        txtProxyHost = new javax.swing.JTextField();
        txtProxyPort = new javax.swing.JTextField();
        txtProxyUser = new javax.swing.JTextField();
        txtProxyPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.ettrema.backup.BackupApplication.class).getContext().getResourceMap(ProxyForm.class);
        pnlOuter.setBackground(resourceMap.getColor("pnlOuter.background")); // NOI18N
        pnlOuter.setName("pnlOuter"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        radUseSystem.setBackground(resourceMap.getColor("radUseSystem.background")); // NOI18N
        proxyGroup.add(radUseSystem);
        radUseSystem.setFont(resourceMap.getFont("radUseSystem.font")); // NOI18N
        radUseSystem.setText(resourceMap.getString("radUseSystem.text")); // NOI18N
        radUseSystem.setName("radUseSystem"); // NOI18N

        radUseCustomSettings.setBackground(resourceMap.getColor("radUseCustomSettings.background")); // NOI18N
        proxyGroup.add(radUseCustomSettings);
        radUseCustomSettings.setFont(resourceMap.getFont("radUseCustomSettings.font")); // NOI18N
        radUseCustomSettings.setText(resourceMap.getString("radUseCustomSettings.text")); // NOI18N
        radUseCustomSettings.setName("radUseCustomSettings"); // NOI18N

        lblProxyHost.setFont(resourceMap.getFont("lblProxyHost.font")); // NOI18N
        lblProxyHost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProxyHost.setText(resourceMap.getString("lblProxyHost.text")); // NOI18N
        lblProxyHost.setName("lblProxyHost"); // NOI18N

        lblProxyPort.setFont(resourceMap.getFont("lblProxyPort.font")); // NOI18N
        lblProxyPort.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProxyPort.setText(resourceMap.getString("lblProxyPort.text")); // NOI18N
        lblProxyPort.setName("lblProxyPort"); // NOI18N

        lblProxyPort1.setFont(resourceMap.getFont("lblProxyPort1.font")); // NOI18N
        lblProxyPort1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProxyPort1.setText(resourceMap.getString("lblProxyPort1.text")); // NOI18N
        lblProxyPort1.setName("lblProxyPort1"); // NOI18N

        lblProxyPort2.setFont(resourceMap.getFont("lblProxyPort2.font")); // NOI18N
        lblProxyPort2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProxyPort2.setText(resourceMap.getString("lblProxyPort2.text")); // NOI18N
        lblProxyPort2.setName("lblProxyPort2"); // NOI18N

        txtProxyHost.setText(resourceMap.getString("txtProxyHost.text")); // NOI18N
        txtProxyHost.setName("txtProxyHost"); // NOI18N

        txtProxyPort.setText(resourceMap.getString("txtProxyPort.text")); // NOI18N
        txtProxyPort.setName("txtProxyPort"); // NOI18N

        txtProxyUser.setText(resourceMap.getString("txtProxyUser.text")); // NOI18N
        txtProxyUser.setName("txtProxyUser"); // NOI18N

        txtProxyPassword.setText(resourceMap.getString("txtProxyPassword.text")); // NOI18N
        txtProxyPassword.setName("txtProxyPassword"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.ettrema.backup.BackupApplication.class).getContext().getActionMap(ProxyForm.class, this);
        jButton1.setAction(actionMap.get("saveAndHide")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jRadioButton1.setBackground(resourceMap.getColor("jRadioButton1.background")); // NOI18N
        proxyGroup.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N

        jButton2.setAction(actionMap.get("closeForm")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout pnlOuterLayout = new javax.swing.GroupLayout(pnlOuter);
        pnlOuter.setLayout(pnlOuterLayout);
        pnlOuterLayout.setHorizontalGroup(
            pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOuterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOuterLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(radUseSystem)
                    .addComponent(radUseCustomSettings)
                    .addGroup(pnlOuterLayout.createSequentialGroup()
                        .addGroup(pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProxyPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlOuterLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblProxyHost, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProxyUser, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(txtProxyPort, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(txtProxyHost, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                    .addGroup(pnlOuterLayout.createSequentialGroup()
                        .addComponent(lblProxyPort2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtProxyPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlOuterLayout.setVerticalGroup(
            pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOuterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radUseSystem)
                .addGap(3, 3, 3)
                .addComponent(radUseCustomSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProxyHost)
                    .addComponent(txtProxyHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProxyPort)
                    .addComponent(txtProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProxyPort1)
                    .addComponent(txtProxyUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProxyPort2)
                    .addComponent(txtProxyPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pnlOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(pnlOuter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void saveAndHide() {
        try {
            proxyDetails.setUseSystemProxy( radUseSystem.isSelected() );
            proxyDetails.setProxyHost( txtProxyHost.getText() );
            proxyDetails.setProxyPort( Integer.parseInt( txtProxyPort.getText() ) );
            proxyDetails.setUserName( txtProxyUser.getText() );
            proxyDetails.setPassword( txtProxyPassword.getText() );
            this.setVisible( false );
        } catch( Exception e ) {
            JOptionPane.showMessageDialog( this, "Couldnt save your proxy details. Please check they are valid" );
        }
    }

    @Action
    public void closeForm() {
        this.setVisible( false );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblProxyHost;
    private javax.swing.JLabel lblProxyPort;
    private javax.swing.JLabel lblProxyPort1;
    private javax.swing.JLabel lblProxyPort2;
    private javax.swing.JPanel pnlOuter;
    private javax.swing.ButtonGroup proxyGroup;
    private javax.swing.JRadioButton radUseCustomSettings;
    private javax.swing.JRadioButton radUseSystem;
    private javax.swing.JTextField txtProxyHost;
    private javax.swing.JTextField txtProxyPassword;
    private javax.swing.JTextField txtProxyPort;
    private javax.swing.JTextField txtProxyUser;
    // End of variables declaration//GEN-END:variables
}
